module meta.utils.runtime_error;

import std.exception;

/* I have no idea what I'm doing :D */